main:
  - identifier: about
    name: About
    url: about
    weight: 1
  - identifier: archive
    name: Archive
    url: archive
    weight: 4
  - identifier: posts
    name: Posts
    url: posts
    weight: 2
