name: netlify

on:
  push:
    branches:
      - feature/hugo-linkcheck

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: peter-evans/link-checker@v1
