name: link check

on:
  schedule:
    - cron: 0 0 * * 6
    # 毎週土曜日のAM9時(JST)

env:
  WEBSITE_URL: "https://nonki-blog.netlify.app/"

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Run Broken Links Checker
        run: npx broken-link-checker $WEBSITE_URL --ordered --recursive --exclude https://t.co/,https://twitter.com/zone_tanichan
        id: link-report
      - name: Get the result
        run: echo "${{steps.link-report.outputs.result}}"
