name: netlify

on:
  push:
    branches:
      - feature/hugo-linkcheck

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Check for broken links
        id: link-report
        uses: celinekurpershoek/github-actions-link-checker@{version}
        with:
          # Required:
          url: "https://nonki-blog.netlify.app/"
          # optional:
          honorRobotExclusions: false
          #ignorePatterns: 'github,google'
      - name: Get the result
        run: echo "${{steps.link-report.outputs.result}}"
